# Generated by Django 3.0.7 on 2020-06-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0004_auto_20200612_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='salt',
            field=models.CharField(default=7, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
