# Generated by Django 3.0.7 on 2020-06-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0006_remove_login_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='salto',
            field=models.CharField(default=8888, max_length=255),
            preserve_default=False,
        ),
    ]
