# Generated by Django 3.0.7 on 2020-06-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0007_login_salto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='salto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
