# Generated by Django 3.0.7 on 2020-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0008_auto_20200612_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='permissions',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.BooleanField(),
        ),
    ]
