# Generated by Django 3.0.7 on 2020-06-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0009_auto_20200620_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='permissions',
            field=models.CharField(default='leitura', max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
