# Generated by Django 3.0.7 on 2020-06-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0010_auto_20200621_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='permissions',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
