# Generated by Django 3.0.7 on 2020-07-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
