# Generated by Django 3.0.7 on 2020-07-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguranca', '0011_auto_20200621_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pessoa_fotos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='seguranca.Login')),
            ],
        ),
    ]
