# Generated by Django 3.0.7 on 2020-07-18 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200717_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.tipo_Person'),
        ),
    ]
