# Generated by Django 3.0.7 on 2020-07-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('coordenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Person')),
            ],
        ),
    ]
