# Generated by Django 3.0.7 on 2020-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='cargahoraria',
            field=models.IntegerField(),
        ),
    ]
