# Generated by Django 3.0.7 on 2020-07-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20200717_2348'),
        ('disciplinas', '0002_auto_20200717_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(to='pessoa.Person'),
        ),
    ]
